name: lab security Bandit check

on: [push]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11.6'
      - name: Run image
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: '1.7.1'
      - name: Install dependencies
        run: poetry install; poetry add pytest; poetry add bandit
      - name: Run Bandit check
        run: poetry run bandit ./app/code.py